# Generated by Django 4.1.7 on 2023-03-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
