# Generated by Django 4.1.7 on 2023-03-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='test',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
