# Generated by Django 4.1.7 on 2023-03-02 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0002_comment_tag_alter_story_images_alter_story_videos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storycomment',
            old_name='feed',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='storyimage',
            old_name='feed',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='storylike',
            old_name='feed',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='storysave',
            old_name='feed',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='storytag',
            old_name='feed',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='storyvideo',
            old_name='feed',
            new_name='story',
        ),
        migrations.CreateModel(
            name='StorySeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='seen',
            field=models.ManyToManyField(related_name='story_seen', through='story.StorySeen', to=settings.AUTH_USER_MODEL),
        ),
    ]
