# Generated by Django 4.1.7 on 2023-02-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_image_remove_feed_image_feedimage_feed_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='images',
        ),
        migrations.AddField(
            model_name='feed',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.image'),
        ),
    ]
