# Generated by Django 4.1.7 on 2023-02-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_feed_images_feed_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='images',
        ),
        migrations.AddField(
            model_name='feed',
            name='images',
            field=models.ManyToManyField(through='feed.FeedImage', to='feed.image'),
        ),
    ]
