# Generated by Django 4.1.7 on 2023-02-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_alter_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='src',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='src',
        ),
    ]
