# Generated by Django 4.1.7 on 2023-02-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_feedsave_feed_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/feed'),
        ),
        migrations.AlterField(
            model_name='video',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to='static/videos/feed'),
        ),
    ]
