# Generated by Django 4.1.7 on 2023-02-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_alter_image_src_alter_video_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='save',
        ),
    ]
