# Generated by Django 4.1.7 on 2023-02-26 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0014_remove_feed_comments_remove_feed_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='comments',
            field=models.ManyToManyField(related_name='feed_comment', through='feed.FeedComment', to='feed.comment'),
        ),
        migrations.AddField(
            model_name='feed',
            name='likes',
            field=models.ManyToManyField(related_name='feed_like', through='feed.FeedLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feed',
            name='saved',
            field=models.ManyToManyField(related_name='feed_save', through='feed.FeedSave', to=settings.AUTH_USER_MODEL),
        ),
    ]
