# Generated by Django 4.1.7 on 2023-02-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_tag_feedtag_feed_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='caption_text',
            field=models.TextField(max_length=5000),
        ),
    ]
