# Generated by Django 4.1.7 on 2023-03-03 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_alter_comment_reply_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/feed', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to='static/videos/feed', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.mp4', '.avi', '.mov'])]),
        ),
    ]
