# Generated by Django 4.1.7 on 2023-03-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_alter_commentreply_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='comment',
        ),
    ]
