# Generated by Django 4.1.7 on 2023-03-11 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0024_remove_commentreply_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.CreateModel(
            name='CommentCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.comment')),
                ('comment_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.commentreply')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(related_name='feed_replies', through='feed.CommentCommentReply', to='feed.commentreply'),
        ),
    ]
