# Generated by Django 4.1.7 on 2023-02-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_username_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
