# Generated by Django 4.1.7 on 2023-02-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
