# Generated by Django 4.1.7 on 2023-02-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='img_cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/cover/'),
        ),
    ]
