# Generated by Django 4.1.7 on 2023-02-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user_img_avatar_user_img_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/avatar/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_cover',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/cover/'),
        ),
    ]
