# Generated by Django 4.1.7 on 2023-03-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_rename_img_cover_user_cover_pic_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_pic_url',
            field=models.ImageField(blank=True, default='static/default/cover_proflie.jpg', null=True, upload_to='static/images/cover/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.ImageField(blank=True, default='static/default/avatar.jpg', null=True, upload_to='static/images/avatar/'),
        ),
    ]
